### PR TITLE
Fixed some README.md

### PR DESCRIPTION
**Pull request by nickksun**
Fixed some instructions of steps besides latest changes in AWS Console.

Especially steps of:
- Create an IAM Role then attach inline policy
- Create a Lambda function (with/without creating a test event)
- Create a Kinesis Firehose delivery stream
- Removed some out-of-date screenshots

Put back missing parameter in DevOps - Module 1 - API Enhancement - 3. Deploy the Unicorn API
(where "--parameter-overrides ProjectId=uni-api" was missing)

Next step:
Put back screenshots with latest content

### CODE REVIEW

**Comment by samdengler** [comment]
👍 for e92d7c5

**Comment by sliedig** [comment]
@nickksun Are you going to add the new screenshots this week?

**Comment by nickksun** [comment]
Added screenshots for WebApplication

**Comment by nickksun** [comment]
Added screenshots for DataProcessing.

All screenshots removed from earlier commits are now resumed by latest version captured from AWS Console on Oct 25, 2017.

**Pull request merged**
