### PR TITLE
Fix lambda function name reference to `RequestUnicorn`

### PR DESCRIPTION
**Pull request by Starefossen**
The Lambda function created in the previous module (module 3) is named `RequestUnicorn` not `RequestRide`. This PR fixes that.

### CODE REVIEW

**Comment by jpignata** [comment]
The step-by-step directions in module 3 actually do say `RequestRide` though the description paragraph above says `RequestUnicorn`. I'd vote to change the single reference to `RequestUnicorn` to match the multiple references to `RequestRide` instead.

**Comment by Starefossen** [comment]
Good catch, @jpignata!

However, have a look at [RequestRide code search](https://github.com/awslabs/aws-serverless-workshops/search?utf8=%E2%9C%93&q=RequestRide&type=) vs. [RequestUnicorn code search](https://github.com/awslabs/aws-serverless-workshops/search?utf8=%E2%9C%93&q=RequestUnicorn&type=).

**Comment by jpignata** [comment]
Hah, fair enough! I defer to @mikedeck.

**Comment by mikedeck** [comment]
Sorry for the delay here, thought I merged this a while ago.

**Pull request merged**
